### ISSUE TITLE
age_player.py: Optimize Player Info API Requests

### ISSUE THREAD

**Issue by Exper1mental** [makayla-moster/HammerBot#1]
Currently `age_player.py` performs 6 JSON API requests sequentially, meaning, one after the other. It looks like this significantly slows the responsiveness of the `!match` command.

Implementing an asynchronous solution where each API request is done at the same time should greatly improve this.

**Comment by makayla-moster** [comment]
I have updated age_player.py in the dev branch, but the command is still not super quick. Unsure if there's something I've missed. 

https://github.com/makayla-moster/HammerBot/blob/development/age_player.py

**Comment by Iapetus-11** [comment]
You should avoid creating multiple aiohttp ClientSessions like you do. You should have one ClientSession which you pass to each function, and you can parallelize these functions with [`asyncio.gather(...)`](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather)

**Comment by makayla-moster** [comment]
Is that how I do this?!

**Comment by Iapetus-11** [comment]
Yep, something like this
```py
async def some_request_func(client_session: aiohttp.ClientSession) -> dict:
    response = await client_session.get("https://some.url.com")
    return await response.json()

async def some_function():
    async with aiohttp.ClientSession() as client_session:
        responses: List[dict] = await asyncio.gather(
            some_request_func(client_session),
            some_request_func(client_session)
        )
```

**Comment by makayla-moster** [comment]
Not fully optimized, but slightly faster than it was.
