### ISSUE TITLE
Add a How to Setup the Bot Guide

### ISSUE THREAD

**Issue by Exper1mental** [makayla-moster/HammerBot#21]
It would be helpful to have some documentation in the README.MD or a separate Contributing.MD covering how to set up the bot for development and testing.

For example, which version(s) of python are verified as being supported? Do any files need to be modified or is additional setup required after forking the repository?

**Comment by makayla-moster** [comment]
Good idea! Not entirely sure how to do this, but I know I need to look into poetry for dependencies and things, which from my understanding will allow everyone to be on the same page.

(Issue 2 for reference)
